### ISSUE TITLE
Автобусны жагсаалт шинэчлэх арга бий юу?

### ISSUE THREAD

**Issue by gracexnn** [EnhboldH/umoney_api#2]

**Comment by khaschuluu** [comment]
Google Maps-руу орчихсон л байсан. Байршлуудыг нь UB smart bus утасны аппынх нь урсгалыг задлаад уншиж болох болов уу гээд горьдоод байгаа.

**Comment by AltangerelG** [comment]
Анхан. Тэгж байгаад задлах гэж үзье даа 😅
